---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - conf.yaml
  - adguard.yaml
  - ingress.yaml
images:
  - name: docker.io/adguard/adguardhome
    newTag: v0.107.67
  - name: docker.io/library/alpine
    newTag: 3.22.2
