---
global:
  leaderElection:
    # Override the namespace used for the leader election lease.
    namespace: cert-manager

crds:
  enabled: true

enableCertificateOwnerRef: true

prometheus:
  enabled: true

  # ServiceMonitor created by kube-prometheus-stack to avoid dependency loops
  servicemonitor:
    enabled: false
