---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: isbtv-secrets
  namespace: isbtv
spec:
  secretTemplates:
    - name: isbtv-secrets
      stringData:
        config.json: ENC[AES256_GCM,data:Gmpbir/a5Tofqm8NVNdareJuyKW0ufXmI4PEwBXN8+YDy5PBjctwPkdlAITBjGiyRUuEunowudWN0N1420oImcJA2qRx5H9Y7ecsXJq7xVcy5CbRXhAF1U6tg2KJ0SQuwu9cJp7/5rwdRArGMqiI9XBJ/OJweSL5fPHY74t76lJ7zQv2J6LzTa+p567RBT00nkLv7fdPMwaBdboDRkWgwCjUtZ1mwYvGwPhRMjtJ6kkQIGrTTnEeYnzn5xchOGKNQF6XBjoyjDq4KlvO6tfHPGjZ5tThH9Q9zzKv9U8Z7s9qOJEK+o6xuCIbB0ey/VaBu98KjWLbjI/SNPMUtoB8XoN0FzVNPmC+aWETnr2wTZkQYzzmyRKxMGxCRFOz5G5qIXQXt35ViA72voJK9+8ybgQxuYg/A+BQkpsAZo1IGhJuVqOGYEvJar3cgngNUCyRpWudBTgAKAPkYysscz77ZOVnhjdaI/s3EwCd4PxbqnUqnqFwf6FF8QuBzct1g31etTp8tHiCujOdObwyLubl0z8y51Wj/3/BdKC4q7N5k0YxV3JWEnhpCJCoVqfLivHrdHKDhcwG4LoGeGmxFfYa9vcUmk/cOlbxuskb0N7LsC+yQvpTv4oKtl2l3/Fl+bFTB20LJpD5dzTIlt7ALHexLUVf2qlhPy1pnwS/c4nLqUVCH4kPtCXV/S47o07L+R5JT/Y1ChhfjgDFSm1y56TZvNvXOs5FTSAV,iv:JPaU91dVpLNsAHJrnMhzSYl44jJJPaJrGYr9MVkR/DQ=,tag:FtW/p3GSuB7XfqZ+XEOSXA==,type:str]
sops:
  age:
    - recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQm15ZUlvV1l5UmhaZXJl
        cHFaOUFNWkJMQ3AweWxwY0YwLzF1YmxCWVRNCmhLR3p6TlZYU1VHWXEvZmJLVHFv
        SWRtVnVlMGVVUlczYTlJZlF5UWRWQzgKLS0tIFVBSTVOS3RnT2wrRXptaVBmNy80
        cjZxOFlORm5tS2JzQjMwWkxuYlZydkUKMlE0fmO3mIq9NhyPVfjRPl8M27Yy4XYg
        1XT57EHk2biWDOqDcgQ1K3QAOczDSVQE9chig1n0LoDWDbPI8gtvLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T09:39:41Z"
  mac: ENC[AES256_GCM,data:64lRbqEkljC1rsXWzv5+1z1FTaE91Y7mcy8dp9FlXhorDYtho0rCZ0G3oJ92hxgU3bMGQw3IXXJI/KuMRrCwtUDKCW/prWFFVNUtaHQHUWl30bLZeEHmXLiVj73LNJeBY8lKG/ch5+JgbcRadH8zWmHLO/vElooA73xJQF6DGQ0=,iv:HEtlaYss80ja+0pLsWR8kXp2PsTNge3AiWKsBEwY6VM=,tag:vGQy17i113P/rANV/mGLvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
