---
apiVersion: v1
kind: Secret
metadata:
  name: diun-secrets
  namespace: diun
  type: Opaque
data:
  notif_telegram_token: "{{ diun_telegram_token | b64encode }}"
  notif_telegram_chatids: "{{ diun_telegram_chatids | b64encode }}"

  regopts_registry_username: "{{ diun_registry_username | b64encode }}"
  regopts_registry_password: "{{ diun_registry_password | b64encode }}"
