---
apiVersion: v1
kind: Secret
metadata:
  name: anime-db-secrets
  namespace: anime
type: Opaque
data:
  POSTGRES_USER: "{{ anime_postgres_user | b64encode }}"
  POSTGRES_PASSWORD: "{{ anime_postgres_password | b64encode }}"

  dsn: "{{ ('host=database user=' + anime_postgres_user + ' password=' + anime_postgres_password + ' dbname=anime port=5432') | b64encode }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secrets
  namespace: anime
type: Opaque
data:
  WIREGUARD_PRIVATE_KEY: "{{ anime_gluetun_wireguard_private_key | b64encode }}"
  WIREGUARD_ADDRESSES: "{{ anime_gluetun_wireguard_addresses | b64encode }}"
  SERVER_COUNTRIES: "{{ anime_gluetun_server_countries | b64encode }}"
  SERVER_CITIES: "{{ anime_gluetun_server_cities | b64encode }}"
  SERVER_HOSTNAMES: "{{ anime_gluetun_server_hostnames | b64encode }}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: anime
  name: anime-registry-secrets
data:
  .dockerconfigjson: "{{ lookup('template', 'misc/dockerconfigjson.json.j2') | tojson | b64encode }}"
type: kubernetes.io/dockerconfigjson
