---
- name: Setup Helm charts
  hosts: ansible_controller
  roles:
    - k8s-helm
  environment:
    # KUBECONFIG: "../../outputs/{{ ansible_environment }}/control-plane/admin.kubeconfig"
  vars:
    k8s_interface: "wg0"
    keys_path: "../../outputs/{{ ansible_environment }}/pki"

    helm_charts:
      - name: cilium
        repo_url: "https://helm.cilium.io/"
        release_name: "cilium"
        chart_name: "cilium/cilium"
        chart_version: "1.15.3"
        namespace: "cilium"
        pre_tasks:
          - install-etcd-secrets.yml
          - gather-etcd-group-nodes.yml
        vars:
          etcd_cafile: "ca-etcd.pem"
          etcd_certfile: "etcd-client-cilium.pem"
          etcd_keyfile: "etcd-client-cilium-key.pem"
          etcd_interface: "{{ k8s_interface }}"
          etcd_client_port: "2379"
          etcd_group: "etcd"
          etcd_secrets_name: "cilium-etcd-secrets"

      - name: coredns
        repo_url: "https://coredns.github.io/helm"
        release_name: "coredns"
        chart_name: "coredns/coredns"
        chart_version: "1.30.0"
        namespace: "kube-system"

      - name: cert-manager
        repo_url: "https://charts.jetstack.io"
        release_name: "cert-manager"
        chart_name: "jetstack/cert-manager"
        chart_version: "1.15.0"
        namespace: "cert-manager"

      - name: traefik
        repo_url: "https://traefik.github.io/charts"
        release_name: "traefik"
        chart_name: "traefik/traefik"
        chart_version: "28.2.0"
        namespace: "traefik"

      - name: longhorn
        repo_url: "https://charts.longhorn.io"
        release_name: "longhorn"
        chart_name: "longhorn/longhorn"
        chart_version: "1.6.2"
        namespace: "longhorn-system"
        pre_tasks:
          - install-dependencies.yml
        post_tasks:
          - create-traefik-ingress.yml
          - create-trim-fs-job.yml

      - name: kube-prometheus-stack
        repo_url: "https://prometheus-community.github.io/helm-charts"
        release_name: "prometheus"
        chart_name: "prometheus-community/kube-prometheus-stack"
        chart_version: "60.4.0"
        namespace: "prometheus"

    helm_tgz_charts:
      - name: porkbun-webhook
        tgz_url: "https://github.com/mdonoughe/porkbun-webhook/releases/download/porkbun-webhook-0.1.4/porkbun-webhook-0.1.4.tgz"
        namespace: "cert-manager"

  pre_tasks:
    - name: Check cluster connection
      shell: "ping -c1 -W1 10.8.2.1"
      register: ping_cluster
      changed_when: false
      failed_when: false

    - name: Join mesh network if needed
      shell: "wg-quick down ../../outputs/{{ ansible_environment }}/wg/apollo/wg0.conf; wg-quick up ../../outputs/{{ ansible_environment }}/wg/apollo/wg0.conf"
      changed_when: false
      when: "ping_cluster.rc != 0"
      become: true
