---
- name: Setup backup host
  hosts:
    - hermes-opti3050m
  roles:
    - restic
  vars:
    types:
      - server
  become: true

  pre_tasks:
    - name: Ensure root user has .ssh directory
      file:
        path: /root/.ssh
        state: directory

    - name: Ensure keypair for restic exists
      community.crypto.openssh_keypair:
        path: /root/.ssh/id

    - name: Register public key
      command: cat /root/.ssh/id.pub
      register: restic_public_key_cmd
      changed_when: false

    - name: Register private key
      command: cat /root/.ssh/id
      register: restic_private_key_cmd
      changed_when: false

    - name: Set fact about keys
      set_fact:
        restic_private_key: "{{ restic_private_key_cmd.stdout }}"
        restic_public_key: "{{ restic_public_key_cmd.stdout }}"
# - name: Setup automatic backups
#   hosts:
#     - controllers
#     - workers
#     # - openwrt TODO??
#   roles:
#     - restic
#   vars:
#     types:
#       - client
#     restic_public_key: "{{ hostvars['hermes-opti3050m'].restic_public_key }}"
#     restic_private_key: "{{ hostvars['hermes-opti3050m'].restic_private_key }}"
#   become: true
