---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: home-assistant
  name: mosquitto-conf
data:
  mosquitto.conf: |
    log_dest stdout
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S

    listener 1883
    protocol mqtt

    allow_anonymous false
    password_file /mosquitto/config/password.txt

    persistence true
    persistence_location /mosquitto/data/
  password.txt: |
    mqtt:$7$101$SCOHoQ4dnDcOJY+B$Yf6mm+znEKQaph/u+qczJolmQJCxX4qcOhpRhKUOu1mvT22BD9QJe+RzHlBURBobenGf/TMVYoD42nsVCO2mgA==
