---
- op: test
  path: /spec/routes/0/match
  value: Host(`ha.kalexlab.xyz`)

- op: replace
  path: /spec/routes/0/match
  value: Host(`ha.dev.kalexlab.xyz`)

- op: remove
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
