---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: certificate.yaml
  - path: ha-ingress.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: home-assistant-ingress
      namespace: home-assistant
  - path: mosquitto-ingress.yaml
    target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRouteTCP
      name: mosquitto
      namespace: home-assistant
