---
- op: test
  path: /spec/routes/0/match
  value: Host(`tasks.kalexlab.xyz`)

- op: replace
  path: /spec/routes/0/match
  value: Host(`tasks.dev.kalexlab.xyz`)

- op: test
  path: /spec/routes/1/match
  value: "Host(`tasks.kalexlab.xyz`) && PathPrefix(`/api`)"

- op: replace
  path: /spec/routes/1/match
  value: "Host(`tasks.dev.kalexlab.xyz`) && PathPrefix(`/api`)"

- op: remove
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
