---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: tasks
  name: kaneo-secrets
spec:
  secretTemplates:
    - name: kaneo-secrets
      stringData:
        AUTH_SECRET: ENC[AES256_GCM,data:jt+gEt/GleCZvphwYNniQjlKQam0Cg74FdATAgAtpyFEMj26j+fLD3PtvAnAUX1j8PK+jLH3S6KEQQD9d6tKLw==,iv:rfDjuxLKccf087PQ/na0NsJ34xhjQc6R+NnyIkfi6sk=,tag:jGWGwY0c+qYPOUR0b1YM3Q==,type:str]
        CUSTOM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:B/IQWIAt4SmN9QzrL9uot8QuDCAcnsCN08fQyXIbWQfxyTx0h7TQ3MG1lDZL8sEGQs1612eNTVBlynpPl0jYeeDTY4IE4qmr,iv:qH+BMd1U9g6LeWrI8KmI6TDV4uA4rIIcO9l3Tzt3sOA=,tag:LiIAYUXQQg5C+M77X17anA==,type:str]
    - name: s3-secrets
      stringData:
        REGION: ENC[AES256_GCM,data:KsYq6BwNNA==,iv:YXQdIFG8f49Mdur+jbTDxSYmYsuh8XiinzUpPWdcsBs=,tag:5Boi9n857uBcxP3VkjSjfw==,type:str]
        ACCESS_KEY: ENC[AES256_GCM,data:SxSIxwZW9WJWH1Qur/ziyezSl0NdhgXAxww=,iv:bHsFsOyT2+aMxJs4k4XMemVJVuFZGOAr+9jeLJ1YeRw=,tag:5Iel8SEU1VspAOT/UJx1FA==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:59dP9vXbcV9bFi2pcVSdXieNr577Ky+72P3iQF8fIRkSdZMnqShaUM/u/hHuGaXK4C0o6LB3n4X3J/InPhX6Ow==,iv:j05QQEmyOLQlAiSdnTQX1Yo4//19LdEs9GITIBVtjoA=,tag:sJDgMqsNqrLbUkJENvCzzg==,type:str]
sops:
  age:
    - recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSGRKNDNhczZjdDBnYU5K
        QzBsczgvWVpnVnkxSXJsTTJLOEdNZU9nWlVVCjhkZXd6R1RxM2JhaFIwY2ZoWTl2
        Wldkai95ZHd2Z3Awb0ZGbmZTNWZua0EKLS0tIEJvdjBpWDc1UmFrZnhEencyV2tB
        OVNaTnd2NTJPNEEyeFFhdUllYkhvUXMK/HlahgFne/YqRJvSiWMsqLnSl0LnttBc
        ucWkPJzdSOn3HLACGI+dAHtyL8QV4CyPAfxBBTafFR0c/O9PZVHTig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T11:47:06Z"
  mac: ENC[AES256_GCM,data:VJs85BYYFPxN7ojvqh7qRHTRZIBQgpfYWUo10WCEfAvSo+/5AHl0+ON4uNl3jxgScW1GU3RI3cxJ0wXVTiygpBrTOjxwqW0aiMr3ivv7T+KS1zwSj7UrNmrgAyAvrW3TE60PoUASBjYXVXAAssc91FhWklOa/sX/PEibABKk2VI=,iv:vM1cvNyERvzHA0n4mS36xumtr3rFjCTU2Cu2neqfG+Q=,tag:4rxcJbNMBhoeWznCAfXaWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
