---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: tasks
  name: kaneo-secrets
spec:
  secretTemplates:
    - name: kaneo-secrets
      stringData:
        AUTH_SECRET: ENC[AES256_GCM,data:c93OWkXCkHTcyf17RvoHG+iRyhmnUCVCHfywo47nYv6bLDXkA06lkE4V88PnDYw2nYSypIDId0B0q0qDCZHuRQ==,iv:PHcSDPTJtv53YdeeYe/xmF8Kld8B89E3opidPIrGV+s=,tag:ZCIdVIfch2rZlOdiAbikbQ==,type:str]
    - name: s3-secrets
      stringData:
        REGION: ENC[AES256_GCM,data:7gbrSSgQRw==,iv:nwksIf1E/z1jCK6yaw000d3iY1Y7KMg7/oz2AJxjYA0=,tag:YC53WLInBN6X+AnMm+tQUw==,type:str]
        ACCESS_KEY: ENC[AES256_GCM,data:ge47S8ALYS+rzk7MLfWEJFSdhSq4MCl/L44=,iv:aePHPxn4LoMipr8ZFtM5YJXGtvnXayE60yCU4vg5C3U=,tag:la1kv7WqwAvQROjHDlmBkQ==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:l083WDjOdnfBqLDSy8gAmNpDxF9MwQloTOUoyKna1qImJx6NDgdVeby4fDZ9/VmpWGT4XtDpdpEOorNgVzqR4g==,iv:GRxfb5btK71oYXzi3OL44Yh/r+7d9hvMST8Dnw+H0Ek=,tag:xI0sNUtk2xOJdrezPOkpKA==,type:str]
sops:
  age:
    - recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnpWZXlWK3NpOVB1WXRO
        Z0V3MVJURlpGb2tmRnRQU1A2N09FSEV1N0NzCnUxK01lUm9lcnJPNVpsWFkxNE5o
        b1pMSlM5YTk0WXBZbDE4Z0M4WEpXdkUKLS0tIGx5WXdlcW9zYzlTcVZZekJESzE2
        S3V3MUlWU1dhT20zdGxTam1CbDVOR00K1LDQ3i6j10WpZo92bwzU/uZ05ZsPz+ja
        PUpw1K7htpkcjXZUpsxeRuiV9hWfVUHygun7Qkb9gUO7pdvIi2/jSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T20:34:09Z"
  mac: ENC[AES256_GCM,data:rwgRPHBLv1pZfR9e6uI3N/0NADqAOsVb2zQ3g32Q8cFYwcAIElHL6eLDsxzkt1PSFpjSRCLn9ZC+s6ySV9jonkYsyIlMxTszgCySpQW/CIS3AgPrrsc1W7IWpnsY05G8gW3cNHhRBKHhYhfDtAcsGF9MEJ1g9BX3jZBl4TVsdmQ=,iv:AFS4GCk7ABKPsKz+Z0B9kxqQSSZD+s6dwJTK1hOtdc4=,tag:jn+NcbX/NjXus/bnfhp2Ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
