---
ansible_environment: prod
local_network: 192.168.10.0/24

traefik_loadbalancer_cidr: 192.168.10.20/32
traefik_loadbalancer_ip: 192.168.10.20

coredns_loadbalancer_cidr: 192.168.10.21/32
coredns_loadbalancer_ip: 192.168.10.21
