---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secrets
  namespace: vaultwarden
type: Opaque
data:
  POSTGRES_USER: "{{ vaultwarden_postgres_username | b64encode }}"
  POSTGRES_PASSWORD: "{{ vaultwarden_postgres_password | b64encode }}"
  DATABASE_URL: "{{ ('postgresql://' + vaultwarden_postgres_username + ':' + vaultwarden_postgres_password + '@database/vaultwarden') | b64encode }}"
