---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backups
  namespace: manga
spec:
  configuration:
    destinationPath: "s3://cnpg/tranga"
    endpointURL: "https://backups.kalexlab.xyz"
    s3Credentials:
      region:
        name: s3-secrets
        key: REGION
      accessKeyId:
        name: s3-secrets
        key: ACCESS_KEY
      secretAccessKey:
        name: s3-secrets
        key: SECRET_KEY
    wal:
      compression: bzip2
    data:
      compression: bzip2
  retentionPolicy: 14d
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: manga
spec:
  inheritedMetadata:
    labels:
      kalexlab.xyz/app: manga
      kalexlab.xyz/component: cluster
      kalexlab.xyz/monitoring: "true"

  instances: 1

  storage:
    storageClass: longhorn
    size: 4Gi

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backups
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-backup
  namespace: manga
spec:
  cluster:
    name: cluster
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
