---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrutiny
  namespace: argocd
  annotations:
    # argocd-image-updater.argoproj.io/image-list: "collector=ghcr.io/analogj/scrutiny:0.x-0, web=ghcr.io/analogj/scrutiny:0.x-0, docker.io/library/alpine:3.x, influxdb=docker.io/library/influxdb:2.x-0"
    argocd-image-updater.argoproj.io/image-list: "docker.io/library/alpine:3.x, influxdb=docker.io/library/influxdb:2.x-0"
    argocd-image-updater.argoproj.io/influxdb.allow-tags: "regexp:^.*-alpine$"
    # Pinning the image name is necessary due to collector and web tags being on the same image name
    # argocd-image-updater.argoproj.io/collector.allow-tags: "regexp:^.*-collector$"
    # argocd-image-updater.argoproj.io/collector.kustomize.image-name: "ghcr.io/analogj/scrutiny:v0.8.0-collector"
    # argocd-image-updater.argoproj.io/web.allow-tags: "regexp:^.*-web$"
    # argocd-image-updater.argoproj.io/web.kustomize.image-name: "ghcr.io/analogj/scrutiny:v0.8.0-web"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  sources:
    - repoURL: "https://github.com/AlessandroZanatta/homelab-v2.git"
      targetRevision: master
      path: kubernetes/monitoring/scrutiny
  destination:
    server: "https://kubernetes.default.svc"
    namespace: scrutiny
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
