---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory" # "https://acme-v02.api.letsencrypt.org/directory"
    email: "{{ cert_manager_email }}"
    privateKeySecretRef:
      name: "{{ cluster_issuer_key }}"
    solvers:
      - selector:
          dnsZones:
            - "{{ cert_manager_dns_zone }}"
        dns01:
          webhook:
            groupName: "{{ cert_manager_group_name }}"
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "{{ cert_manager_email }}"
    privateKeySecretRef:
      name: "{{ cluster_issuer_key }}"
    solvers:
      - selector:
          dnsZones:
            - "{{ cert_manager_dns_zone }}"
        dns01:
          webhook:
            groupName: "{{ cert_manager_group_name }}"
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key
