---
# https://github.com/dag-andersen/argocd-diff-preview?tab=readme-ov-file#basic-usage-in-a-github-actions-workflow
name: Argo CD Diff Preview

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          path: pull-request

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Prepare cluster secrets
        run: |
          set -euo pipefail

          mkdir secrets
          yq eval '.cluster.inlineManifests[1].contents' -r ${{ github.base_ref }}/talos/patches/cluster/env.yaml | yq '.metadata.labels.env = "dev"' > secrets/cluster.yaml

      - name: Prepare ArgoCD values
        run: |
          set -euo pipefail

          ENCODED_SOPS_SECRET=$(echo -ne "${{ secrets.SOPS_SECRET }}" | base64 -w0)
          yq ".extraObjects[0].data.\"sops.agekey\" = \"$ENCODED_SOPS_SECRET\"" ${{ github.base_ref }}/helm/argocd/values.yaml |
            yq '.configs.params."server.insecure" = false' > values.yaml

      - name: Generate Diff
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/${{ github.base_ref }}:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -v $(pwd)/secrets:/secrets \
            -v $(pwd)/values.yaml:/argocd-config/values.yaml \
            -e TARGET_BRANCH=refs/pull/${{ github.event.number }}/merge \
            -e BASE_BRANCH=${{ github.base_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:latest

      - name: Post diff as comment
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
